### ISSUE TITLE
How to / documentation

### ISSUE THREAD

**Issue by BigManatee** [billythekid/v12finance#1]
I'm trying to find a API wrapper in PHP for v12 and it has been a major struggle but I've now found yours!

Do you happen to have any examples on how to use this or any kind of documentation?

**Comment by billythekid** [comment]
Hi @RoofTyler, I've just pushed the [generated API docs](https://billythekid.github.io/v12finance/docs/namespaces/billythekid.v12finance.html) from my phpdocumentor for you which will give you a slight overview of the actual classes and so forth. 

I'll push an update to the readme with some example code that should hep you.

Please feel free to PR anything I never got to, the client I was building this for recently moved their finance option to another product so this package isn't 100% complete yet. Hopefully it has the guts of what you need however.

**Comment by RoofTyler** [comment]
Thanks so much @billythekid! I'll get to reading and testing.
If I have to add anything I'll definitely make some PRs

**Comment by billythekid** [comment]
That's some example code (from my own debugging, lol) on the readme. I hope this at least gets you a bit of a start, even around getting your head around just what the heck this finance application stuff is even all about! lol

**Comment by billythekid** [comment]
That's it [up on packagist](https://packagist.org/packages/billythekid/v12finance) too now so if you need to pull it in to a composer project it should be a bit easier for you now too.

`composer require billythekid/v12finance`

**Comment by billythekid** [comment]
Heya @BigManatee 👋 

Just wondering if you did end up using this in your project and if so, if you finished the bits off that are still to be done on this one? The original client I did this for is apparently thinking of switching back to V12 so there's a chance I'd be looking to reactivate this project as I'll still need some V12 PHP wrapper to use in a Craft Commerce plugin. 

Figured I should ask if I can avoid reinventing any wheels or not!

Cheers,
Billy 🤠

**Comment by BigManatee** [comment]
Hey @billythekid!

Sadly I didn't.
The company I was integrating this for shortly decided against v12 after I created this issue so nothing came of it but I do remember for the brief time I was using this wrapper, it was pretty smooth!

Sorry for not being much help but hopefully not much has changed and adding extra requirements isn't too bad!

**Comment by billythekid** [comment]
Ah no worries @BigManatee. Thanks very much for getting back to me though, appreciate it!
